language: python

python:
  - 3.6
  - 3.7

install:
  - source prepareenv.sh
  - source .github/travis/check_license.sh
  - source .github/travis/check_python_script.sh

script:
  - conda activate yosys-env
  - which tox
  - TOXENV="py${TRAVIS_PYTHON_VERSION//./}" tox

notifications:
  email: false
